cmd:
- /nfs/bartesaghilab2/ds672/anaconda3/envs/cryodrgn/bin/cryodrgn
- train_vae
- /nfs/bartesaghilab2/ds672/master/delete_me/example_1000/particles_example_1000.mrc
- --ctf
- /nfs/bartesaghilab2/ds672/master/delete_me/example_1000/ctf_1000.pkl
- --poses
- /nfs/bartesaghilab2/ds672/master/delete_me/example_1000/poses_1000.pkl
- --zdim
- '8'
- -n
- '2'
- --enc-dim
- '256'
- --enc-layers
- '3'
- --dec-dim
- '256'
- --dec-layers
- '3'
- --load
- /weights.1.pkl
- --uninvert-data
- -o
- ''
dataset_args:
  ctf: /nfs/bartesaghilab2/ds672/master/delete_me/example_1000/ctf_1000.pkl
  datadir: null
  do_pose_sgd: false
  ind: null
  invert_data: false
  keepreal: false
  norm:
  - 0.0
  - 347.81988525390625
  particles: /nfs/bartesaghilab2/ds672/master/delete_me/example_1000/particles_example_1000.mrc
  poses: /nfs/bartesaghilab2/ds672/master/delete_me/example_1000/poses_1000.pkl
  window: true
  window_r: 0.85
lattice_args:
  D: 129
  extent: 0.5
  ignore_DC: true
model_args:
  activation: relu
  domain: fourier
  enc_mask: 64
  encode_mode: resid
  feat_sigma: 0.5
  pdim: 256
  pe_dim: null
  pe_type: gaussian
  players: 3
  qdim: 256
  qlayers: 3
  tilt_params:
    ntilts: 10
    t_emb_dim: 64
    tdim: 1024
    tlayers: 3
  zdim: 8
seed: 61182
time: 2025-06-11 16:09:49.598904
version: 3.4.3
